### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by felquis** [raphamorim/inphinity#10]
Browser Chrome Version 45.0.2454.101 (64-bit)
Platform: OSX Yosemite 10.10.5
### How to reproduce
- Access http://raphamorim.com/blog/ && Open DevTools
- Scroll to down
- Click Next

Console outputs this message

> Inphinity:  Sorry, we couldn't parse your Next (Previous Posts) URL.

**Comment by raphamorim** [comment]
Yeah, this is a problem.

Currently if you change the page, the Inphinity doesn't detect that you're in a different page and continues searching for data as if you were on the first page.

**Comment by raphamorim** [comment]
Solved in e2a48e1c7f059b3f93c9eb41ab202f92c352fffe
