### ISSUE TITLE
Wrap everything inside an IIFE and UMD export

### ISSUE THREAD

**Issue by mauriciosoares** [raphamorim/inphinity#7]
Hey, nice project...

Today you export 2 global variables, the Contructor `Inphinity` and the instance `inphinity`. Should them both be in the global scope? maybe if you wrap everything into an [IIFE](http://benalman.com/news/2010/11/immediately-invoked-function-expression/) you can only export the one that's actually gonna be used by the developer.

Also you can add UMD support on it, adding a simple [snippet](https://github.com/umdjs/umd), or even add it to your [build process](https://github.com/eduardolundgren/gulp-umd) (which is nicer in my opinion)

Cheers!

**Comment by raphamorim** [comment]
Yiips!

Good AND vital suggestion! Initially the code started using IIFFE. But I've removed to test the functions individually. In the end: I've forgotten to put back :/

I'll update this in next commit. Thanks @mauriciosoares !

**Comment by raphamorim** [comment]
Oh, about UMD support. I'll see. 
Note: I like the build process option.

**Comment by mauriciosoares** [comment]
![borat-thumbs-up-meme-photos-2](https://cloud.githubusercontent.com/assets/2321259/9151264/f3a5cc5c-3dd2-11e5-9a61-a8ffb015e964.jpg)

**Comment by mauriciosoares** [comment]
I was going to close this issue, but I'll keep it opened, so you can close it when you implement what you want :)

**Comment by raphamorim** [comment]
+1 in borat image hahaha

**Comment by raphamorim** [comment]
Updated in 4ca07737161462a7688c91b78676ecfd3d66928f. 
About UMD support, I'll create another issue and apply a reference here.

**Comment by raphamorim** [comment]
Anyway thanks @mauriciosoares :)

**Comment by mauriciosoares** [comment]
great job! keep up the good work 

😎
