### ISSUE TITLE
Use DocumentFragment

### ISSUE THREAD

**Issue by leaofelipe** [raphamorim/inphinity#8]
What about use DocumentFragment to include new Elements to DOM? We can increase performance on the DOM Manipulation.

**Comment by raphamorim** [comment]
I've used, but not work well for most cases. Generating parser errors in most cases.

**Comment by raphamorim** [comment]
However, I'll see it again. Maybe I can adjust string before parsing.

**Comment by leaofelipe** [comment]
Hmm... Good to Know!

**Comment by raphamorim** [comment]
I tried again, But as we don't know what kind of data/elements will come. Setting these elements is quite costly in file size.

The current goal is to let Inphinity more lighter :)

**Comment by leaofelipe** [comment]
Okay boss!
Em 14/10/2015 4:25 AM, "Raphael Amorim" notifications@github.com escreveu:
